### PR TITLE
feature(pwa): add app manifest and favicons

### PR DESCRIPTION
**Pull request by aciccarello**
## Description
Used http://realfavicongenerator.net/ to generate a manifest file and added some icons. Since the generated output was a bit overkill I tried to pair down the icons used. I could remove more if desired. This was done to improve the Lighthouse score #57

### What's included?

- manifest.json file
- Standalone covalent-quickstart svg icon
- Several icon sizes
- Updated metadata in index.html

#### Test Steps

- [ ] Install [Lighthouse chrome extension](https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk/)
- [ ] ng serve
- [ ] Run lighthouse test

##### Screenshots or link to CodePen/Plunker/JSfiddle
Lighthouse score can be seen at https://googlechrome.github.io/lighthouse/viewer/?gist=cd54712c26b1cc4475eea300b615ac3e though it was done on localhost so there is no https

### CODE REVIEW

**Comment by kyleledbetter** [comment]
awesome idea @aciccarello testing...

**Comment by kyleledbetter** [comment]
Hmmm when i try to `ng serve` i'm getting
```
ERROR in Cannot read property 'getSymbolByModule' of undefined
webpack: Failed to compile.
```

**Comment by aciccarello** [comment]
@kyleledbetter That is an unrelated problem with angular 4.0.2 (see angular/angular-cli#5940). It only affects the initial build.

**Comment by emoralesb05** [comment]
Forgot about this, gonna merge it 😄

**Pull request merged**
