### PR TITLE
update ngx-charts to from 3.1.2 to 4.01

### PR DESCRIPTION
**Pull request by dhcdata**
## Description
Update ngx-charts version from 3.1.2 to 4.0.1. Renamed ngx-charts.css to index.css in angular-cli.json

### CODE REVIEW

**Comment by emoralesb05** [comment]
There is an issue with `ngx-charts` atm that breaks `aot` builds.

I opened an issue for that https://github.com/swimlane/ngx-charts/issues/194#issuecomment-275914083 to keep track of it.

**Comment by emoralesb05** [comment]
This is actually not blocked anymore and it works fine in `4.1.1` 😄 

Can you just resolve the conflict and remove the `index.css` style? Its not needed anymore.

**Comment by dhcdata** [comment]
This has already been addressed.

https://github.com/Teradata/covalent/commit/3f0ace5b4b3e599a99a4761891d897abaa05c938

**Comment by emoralesb05** [comment]
Well, thats been addressed there, but its still needed in the quickstart.

**Pull request closed without merging**
