### PR TITLE
refactored(): updated project dependencies

### PR DESCRIPTION
**Pull request by jotatoledo**
* Updated to latest material, flex layout, ngx charts and covalent versions
* Refactored app module to use a shared module (pre-step for lazy loaded modules)
* Added shared module

### CODE REVIEW

**Comment by jotatoledo** [comment]
Still not green on `ng test`

**Comment by emoralesb05** [comment]
Thanks for the PR man! with upgrade bonus haha 😄

**Comment by jotatoledo** [comment]
Im considering to make another one (on the not so near future 😄 ) to move the services into the app folder and create at least one lazy loaded module as showcase

**Comment by emoralesb05** [comment]
awesome man, looking forward for it.

**Pull request merged**
