### PR TITLE
core(dependencies): updated

### PR DESCRIPTION
**Pull request by jotatoledo**
Updated dependencies to latest, fixed lint errors, reworked config files to match the ones generated by cli 1.3.0.

I still would like to make some mayor refactorings to the folder structure and internal modules of the application, but maybe that could be made in another pr.

@emoralesb05 if you agree with the 2nd point, I could make some sketch or similar to show what I have in mind.

### CODE REVIEW

**Comment by emoralesb05** [comment]
Thank god for people like you dude haha
im down for the refactor for sure, but def in a separate PR after we merge this, gonna test this later today 😄

**Comment by ianqueue** [comment]
by "refactorings to the folder structure", do we mean a more module style of organization?  That's what we are doing and I agree it would clean up a lot of app.module and set people up better from the start.

**Comment by jotatoledo** [comment]
Yup, separafe feature modules and create a core/sharedmodule if necessary

_Sent from my Huawei ALE-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by emoralesb05** [comment]
Hey man, can you fix the conflicts so we can test this again and merge it? Merged the karma updates first and it clashed with this one 😢

**Comment by jotatoledo** [comment]
@emoralesb05 next week Ill have some time, for now my hands are tight up. Btw, any news about my pr in the covalent repo? 😢  I was thinking about adding some examples, but I wouldnt like to expend time on it withouth knowing if the pr will see the light or not 😄

**Comment by emoralesb05** [comment]
Yeah, im jumping into it this week 😄  attacked a few things this weekend that affected the build process, and now we are focusing on the IE11 issues for the most part.

**Comment by jotatoledo** [comment]
@emoralesb05 Ill wait for the new release of covalent to work on this

**Comment by emoralesb05** [comment]
Yeah, sounds like a good idea 😄 Im working on the data-table PR today so we can finish it and release ASAP

**Comment by jotatoledo** [comment]
closing in favor of the latest updates

**Pull request closed without merging**
