### PR TITLE
Feature/1.0.0 beta.2

### PR DESCRIPTION
**Pull request by merqlove**
- [x] Add yarn.
- [x] Fix tests.
- [x] Fix e2e install.
- [x] Fix 1.0-rc0 integration.

### CODE REVIEW

**Comment by merqlove** [comment]
@kyleledbetter, hi

**Comment by kyleledbetter** [comment]
Hi @merqlove sry, we've been quite busy at our day jobs :P  Thx so much for the PR

@emoralesb05 @richavyas @ilsiepotamus @indyplanets @jeremysmartt can a couple of you code review & test pls?

**Comment by jeremysmartt** [comment]
@kyleledbetter 

I reviewed code and tested.

LGTM

**Comment by kyleledbetter** [comment]
merged, thx @merqlove !

**Pull request merged**
