### PR TITLE
Lint rule and fixes

### PR DESCRIPTION
**Pull request by richavyas**
## Description

- Modified Lint rule
- Lint fixes
- Data files, yaml files, components modifications for variables' name change

Test Steps
- [x] `npm run stop-api`
- [x] `npm run start-api` to get updated mock data
- [x] `ng serve`
- [x] Navigate to http://localhost:4200/users and see if everything is working after data, component & html modifications
- [x] npm run lint and see everything is passing

### CODE REVIEW

**Comment by kyleledbetter** [comment]
test steps?

**Comment by richavyas** [comment]
- [x] Added Test step

**Comment by kyleledbetter** [comment]
thx i was running `npm run test` thinking it covered both. When i run `npm run lint` i get:
```
> covalent-quickstart@1.0.0-beta.1 lint /Users/kyleledbetter/Sites/covalent-quickstart
> tslint -c ./tslint.json "./src/**/*.ts" -e "./src/**/typings.d.ts" -e "./src/environments/**"


src/app/users/+form/form.component.ts[17, 3]: variable name must be in camelcase or uppercase
src/app/users/+form/form.component.ts[53, 9]: variable name must be in camelcase or uppercase
```

**Comment by kyleledbetter** [comment]
when i view http://localhost:4200/#/product/features
i'm getting
```
error_handler.js:54 EXCEPTION: Error in ./ProductFeaturesComponent class ProductFeaturesComponent - inline template:2:8 caused by: Cannot read property 'filter' of undefined
ErrorHandler.handleError @ error_handler.js:54
next @ application_ref.js:359
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:331
onHandleError @ ng_zone.js:292
ZoneDelegate.handleError @ zone.js:246
Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:345
data.args.(anonymous function) @ zone.js:1376
error_handler.js:56 ORIGINAL EXCEPTION: Cannot read property 'filter' of undefined
```

**Pull request merged**
